#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys, re

commitMessageFile = open(sys.argv[1]) 
commitMessage = commitMessageFile.read().strip()

result_list =  commitMessage.split(':')
if len(result_list) < 3:
  print "error:请以'type:module:message'三段式提交，如fix:个人主页角色卡:帧动画加载失败修复，当前提交只有%d段。"%(len(result_list))
  sys.exit(1)

c_type = result_list[0]
type_list = ['feat','fix','docs','style','refactor','test','chore']
type_str = ' '.join(type_list)
if c_type not in type_list:
  print "error:第一个字段type用以说明类型，'%s'不合法，请使用%s 7个标识之一"%(c_type,type_str)
  sys.exit(1)